trigger:
  branches:
    include:
    - main
  paths:
    include:
    - iac/wwe-ga/*
    - iac/modules
    exclude:
    - iac/wwe-egos/*
    - iac/dr_network/*
    - iac/shared_network_dr/*
    - pipelines/*

resources:
  repositories:
  - repository: commonTerraform
    type: git
    name: Common.Terraform
  - repository: commonPipeline
    type: git
    name: Common.Pipelines

variables:
  # ========================================================================
  #                          Mandatory variables 
  # ========================================================================
- name: poolImage
  value: 'windows-latest'
- name: pool
  value: 'ap-wwe-prd'
- name: TerraformStateContainer
  value: 'ga'
#sets the terraform version for use across the entire pipeline
- name: terraformVersion 
  value: 1.9.5

stages:
- template: ./templates/deployEnv-wwe-ga.yaml
  parameters:
    stage_name: Prod_Deploy_WWE_GA
    depends_on: []
    environment_name: 'WWE_GA_Prod'
    AzureServiceConnection: 'ASC-WWE-Prod' #Platform Service Connection
    AzureRegion: eastus2
    SubscriptionId: '6f9f1e7d-bfc5-4c84-a02f-93152a27b55d' #wwe-prod Subscription Id
    Environment: 'prod'
    OrganizationalPrefix: 'wwe'
    BootstrapAzureRegion: eastus2
    TerraformBackingStoreContainerName: '$(TerraformStateContainer)-eastus2'

- template: ./templates/deployEnv-wwe-ga.yaml
  parameters:
    stage_name: Prod_Deploy_WWE_GA_DR
    depends_on: [Prod_Deploy_WWE_GA]
    environment_name: 'WWE_GA_Prod'
    AzureServiceConnection: 'ASC-WWE-Prod' #Platform Service Connection
    AzureRegion: centralus
    SubscriptionId: '6f9f1e7d-bfc5-4c84-a02f-93152a27b55d' #wwe-prod Subscription Id
    Environment: 'prod'
    OrganizationalPrefix: 'wwe'
    BootstrapAzureRegion: eastus2
    TerraformBackingStoreContainerName: '$(TerraformStateContainer)-centralus'

