trigger:
  branches:
    include:
    - main
  paths:
    include:
    - iac/wwe-shared/*
    exclude:
    - iac/wwe-ga/*
    - iac/wwe-dr/*
    - pipelines/*

resources:
  repositories:
  - repository: commonTerraform
    type: git
    name: Common.Terraform
  - repository: commonPipeline
    type: git
    name: Common.Pipelines

variables:
  # ========================================================================
  #                          Mandatory variables 
  # ========================================================================
- name: poolImage
  value: 'windows-latest'
- name: pool
  value: 'ap-wwe-prd'
- name: TerraformStateContainer
  value: 'shared'
#sets the terraform version for use across the entire pipeline
- name: terraformVersion 
  value: 1.9.5

stages:
- template: ./templates/deployEnv-wwe-shared.yaml
  parameters:
    stage_name: prod_Deploy_WWE_SHARED
    depends_on: []
    environment_name: 'WWE_Shared_Prod'
    AzureServiceConnection: 'ASC-WWE-Prod' #Platform Service Connection
    AzureRegion: eastus2
    SubscriptionId: '6f9f1e7d-bfc5-4c84-a02f-93152a27b55d' #wwe-prod Subscription Id
    Environment: 'prod'
    OrganizationalPrefix: 'wwe'
    BootstrapAzureRegion: eastus2
    TerraformBackingStoreContainerName: '$(TerraformStateContainer)-eastus2'

- template: ./templates/deployEnv-wwe-shared.yaml
  parameters:
    stage_name: prod_Deploy_WWE_SHARED_DR
    depends_on: [prod_Deploy_WWE_SHARED]
    environment_name: 'WWE_Shared_Prod'
    AzureServiceConnection: 'ASC-WWE-Prod' #Platform Service Connection
    AzureRegion: centralus
    SubscriptionId: '6f9f1e7d-bfc5-4c84-a02f-93152a27b55d' #wwe-prod Subscription Id
    Environment: 'prod'
    OrganizationalPrefix: 'wwe'
    BootstrapAzureRegion: eastus2
    TerraformBackingStoreContainerName: '$(TerraformStateContainer)-centralus'

